server:
    port: ${PORT:8091}

spring:
    application:
        name: microservice-comment
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
        username: postgres.uvaiaecevrtliujmrllw
        password: rMQ0aAPZ39GKI3m1
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
    secret: my-super-secret-key-which-is-long-enough-1234567890

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs