server:
    port: ${PORT:8091}

spring:
    application:
        name: microservice-comment
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${URL_DB}
        username: ${USERNAME_DB}
        password: ${PASSWORD_DB}
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
    secret: ${JWT_SECRET}

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs