server:
    port: 8092

spring:
    application:
        name: microservice-comment
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${URL_DB}
        username: ${USERNAME_DB}
        password: ${PASSWORD_DB}
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    config:
        import: "optional:configserver:http://localhost:8888"

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

jwt:
    secret: my-super-secret-key-which-is-long-enough-1234567890

springdoc:
  swagger-ui:
      path: /swagger-ui.html
  api-docs:
      path: /api-docs
