server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: microservice-user
            uri: ${API_USER_URI:https://microservice-user-bnud.onrender.com}
            predicates:
              - Path=/api/auth/**

          - id: microservice-comment
            uri: ${API_COMMENT_URI:https://microservice-comment.onrender.com}
            predicates:
              - Path=/api/comentarios/**



