server:
  port: ${PORT:8091}

spring:
  application:
    name: microservice-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UsuarioDB
    username: postgres
    password: 3201
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: my-super-secret-key-which-is-long-enough-1234567890
  expiration: 3600000

springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs
