name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Packages/frontend/package-lock.json

      - name: Install dependencies
        working-directory: Packages/frontend
        run: npm ci

      - name: Build frontend
        working-directory: Packages/frontend
        run: npm run build

      - name: Deploy to Vercel
        uses: vercel/action@v2
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: Packages/frontend
          prod: true

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Verificar carpeta backend
        run: |
          if [ ! -d "Packages/backend" ]; then
            echo "❌ El directorio Packages/backend no existe"
            exit 1
          fi

      - name: Build backend
        working-directory: Packages/backend
        run: mvn clean install
