name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERCEL_ORG_ID:    ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          echo "Checking frontend directory:"
          ls -la Packages/frontend

      - name: Setup Node.js and cache npm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Packages/frontend/package-lock.json

      - name: Install dependencies and Vercel CLI
        run: |
          cd Packages/frontend
          npm ci
          npm install -g vercel@latest

      - name: Pull Vercel environment variables
        run: |
          cd Packages/frontend
          vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Build frontend
        run: |
          cd Packages/frontend
          vercel build --prod --yes --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy frontend
        run: |
          cd Packages/frontend
          vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java (Temurin 21)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify backend directory exists
        run: |
          if [ ! -d "Packages/backend" ]; then
            echo "❌ El directorio Packages/backend no existe"
            exit 1
          fi

      - name: Build backend with Maven
        run: |
          cd Packages/backend
          mvn clean install
